#! /usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);


#link to servi2adjust and template2expand
for  my $event (qw( dhcp-dns ))
{
    # services to launch on event
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/dnscache");
    safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/tinydns");
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/dhcpd");
    
    # actions to perform
    safe_symlink("../actions/dnscache-change", "root/etc/e-smith/events/dhcp-change/S20dnscache-change");

    # Template to event
    templates2events("/var/service/tinydns/root/data", $event);
}

#creation of dhcp-dns service
    safe_symlink("daemontools", "root/etc/rc.d/init.d/dhcp-dns");
    service_link_enhanced("dhcp-dns", "S85", "7");
    service_link_enhanced("dhcp-dns", "K25", "6");
    service_link_enhanced("dhcp-dns", "K25", "0");
    safe_symlink("/var/service/dhcp-dns/", "root/service/dhcp-dns");
