#! /usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);


#link to servi2adjust and template2expand
for  my $event (qw( dhcp-change ))
{
    # services to launch on event
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/dnscache");
    safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/tinydns");
    # actions to perform
    safe_symlink("../actions/dnscache-change", "root/etc/e-smith/events/dhcp-change/20dnscache-change");
}
