#!/usr/bin/perl

my $lease_file = "/var/lib/dhcpd/dhcpd.leases";

# last modified time
my $modtime = 0;

# seconds to wait
my $update_freq = 15;

###########################################################################
# Main Loop
while (1) {

  # check the file's last updated time, if it's been changed, update
  # the DNS and save the modified time.  This will ALWAYS run once - on
  # startup, since $modtime starts at zero.

  my @stats = stat ($lease_file);
  if ($stats[9] > $modtime) {
  
  	$modtime = $stats[9];

        system ("/usr/bin/sv 1 /service/tinydns");
  }

  # wait till next check time
  sleep $update_freq;

} # end main
###########################################################################


